<?php
// Copyright 1999-2017. Parallels IP Holdings GmbH.
?>
<div id="googleurlshortener" class="form">
    <div class="logo">
        <img src="<?php echo pm_Context::getBaseUrl(); ?>images/google-url-shortener-logo.png" alt="Google URL Shortener"/>
    </div>
    <div>
        <?php echo $this->output_description; ?>
    </div>
    <?php if (!empty($this->output_description_api)) : ?>
        <?php echo $this->output_description_api; ?>
    <?php endif; ?>
    <?php echo $this->form; ?>
    <div class="change-api-key">
        <?php echo $this->change_api; ?>
    </div>
    <div>
        <?php echo $this->renderList($this->list); ?>
    </div>
</div>
